# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Halo < Formula
  desc "Control plane for AI coding CLIs (Claude Code, Codex, Gemini)"
  homepage "https://dshakes.github.io/halos"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dshakes/halos/releases/download/v0.1.1/halo_0.1.1_darwin_amd64.tar.gz"
      sha256 "f0d4ea70ece3d073ebdb7209a4d760349e03af3efbadce4a432fa8977fd3281b"

      define_method(:install) do
        bin.install "halo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dshakes/halos/releases/download/v0.1.1/halo_0.1.1_darwin_arm64.tar.gz"
      sha256 "b91a88ba7fb8b6b23c23679c5989404a70f36fa22b01e5c3ad7ab3642cf27955"

      define_method(:install) do
        bin.install "halo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dshakes/halos/releases/download/v0.1.1/halo_0.1.1_linux_amd64.tar.gz"
      sha256 "ecfc30979ec978fac344f31e1b770a2df62579b6987fea6511801c08f2ca007d"
      define_method(:install) do
        bin.install "halo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dshakes/halos/releases/download/v0.1.1/halo_0.1.1_linux_arm64.tar.gz"
      sha256 "c06d9006c9ff179fa28393f9bc4b126a92c48d3fc6a412ce9c52e96b99801232"
      define_method(:install) do
        bin.install "halo"
      end
    end
  end

  test do
    system "#{bin}/halo", "version"
  end
end
