# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Halo < Formula
  desc "Control plane for AI coding CLIs (Claude Code, Codex, Gemini)"
  homepage "https://dshakes.github.io/halos"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dshakes/halos/releases/download/v0.1.1/halo_0.1.1_darwin_amd64.tar.gz"
      sha256 "9041e79df2bb37fe2e3344004a900cacdab94d7c31c5196931289f9a9c015ec8"

      define_method(:install) do
        bin.install "halo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dshakes/halos/releases/download/v0.1.1/halo_0.1.1_darwin_arm64.tar.gz"
      sha256 "ee8dfb6d41698ddcce027ce77f9f2219024c4847d3e743a4adb0f757c5123a18"

      define_method(:install) do
        bin.install "halo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dshakes/halos/releases/download/v0.1.1/halo_0.1.1_linux_amd64.tar.gz"
      sha256 "b2490c61fb6c67f0866251fd3939ba7af0b934c3255393a324d06bb544daf039"
      define_method(:install) do
        bin.install "halo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dshakes/halos/releases/download/v0.1.1/halo_0.1.1_linux_arm64.tar.gz"
      sha256 "74f7e1c461ce6ba162a6095388435d8432234203d1b25429aba3072d968abe55"
      define_method(:install) do
        bin.install "halo"
      end
    end
  end

  test do
    system "#{bin}/halo", "version"
  end
end
